In [2]:
import numpy as np

In [4]:
arr1=np.array([12,45,67])
arr2=np.array([23,56,78])
print("Array 1:", arr1)
print("Array 2:", arr2)

Array 1: [12 45 67]
Array 2: [23 56 78]


In [7]:
import numpy as np
arr=np.array([[1,23,45],[2,34,56],[3,45,67]])
print(arr.shape)


(3, 3)


In [9]:
np.arange(1,10,2).reshape(5,1)  # Creates an array with values from 1 to 9 with a step of 2

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [11]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.ones((3, 4))  # Creates a 3x4 array filled with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#Attributes of numpy arrays
import numpy as np
arr=np.array([[1,2,3,4,5,6,3,2,21,1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]])
print("Array:", arr)
print("Shape:", arr.shape)  # Shape of the array
print("Dimension number:",arr.ndim)
print("Size(No of elements)",arr.size)
print("Data type of elements:", arr.dtype)  # Data type of the elements in the array
print("Item size:", arr.itemsize)  # Size of each item in bytes     
print("Total bytes consumed by the array:", arr.nbytes)  # Total bytes consumed by the array

Array: [[ 1  2  3  4  5  6  3  2 21  1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
Shape: (2, 19)
Dimension number: 2
Size(No of elements) 38
Data type of elements: int64
Item size: 8
Total bytes consumed by the array: 304


In [23]:
#Vectorized operations
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5] )
arr2 = np.array([6, 7, 8, 9, 10])
print("ADD",arr1+arr2)
print("SUBTRACT",arr1-arr2)
print("MULTIPLY",arr1*arr2)
print("DIVIDE",arr1/arr2)      
print("SQUARE ROOT",np.sqrt(arr1))
print("EXPONENT",np.exp(arr1))  # Exponentiation      
print("LOGARITHM",np.log(arr1))  # Natural logarithm
print("LOG10",np.log10(arr1))  # Base-10 logarithm      
print("SINE",np.tan(arr1))  # Tan function

ADD [ 7  9 11 13 15]
SUBTRACT [-5 -5 -5 -5 -5]
MULTIPLY [ 6 14 24 36 50]
DIVIDE [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
SQUARE ROOT [1.         1.41421356 1.73205081 2.         2.23606798]
EXPONENT [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
LOGARITHM [0.         0.69314718 1.09861229 1.38629436 1.60943791]
LOG10 [0.         0.30103    0.47712125 0.60205999 0.69897   ]
SINE [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [29]:
#Array Indexing and Slicing
import numpy as np  
arr=np.array([[1,2,3,4,5],[7,5,4,3,2],[6,7,8,9,10]])
arr[1:,2:]

array([[ 4,  3,  2],
       [ 8,  9, 10]])

In [46]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original Array:\n", arr)
print("First Row:", arr[0])  # Accessing the first row  
print("First Column:", arr[:, 0])  # Accessing the first column
arr[1:3,1:3]

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First Row: [1 2 3 4]
First Column: [1 5 9]


array([[ 6,  7],
       [10, 11]])

In [51]:
#Modifying Array Elements
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)
arr[0,2]=12
print(arr)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2 12]
 [ 4  5  6]
 [ 7  8  9]]


In [57]:
#Practise(slicing and indexing
import numpy as np
arr = np.array([[1, 2, 3,4,5], [4, 5, 6,7,8], [7, 8, 9,10,11]])
print("Original Array:\n", arr)
arr[1, 2] = 20   # Modifying a specific element
print("Modified Array:\n", arr)

Original Array:
 [[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]
Modified Array:
 [[ 1  2  3  4  5]
 [ 4  5 20  7  8]
 [ 7  8  9 10 11]]


In [59]:
#stat
import numpy as np
arr = np.array([1, 2, 3,4,5])
print("Original Array:\n", arr)
print("Mean:",np.mean(arr))
print("St deviation:",np.std)
nor=(arr-np.mean(arr))/np.std(arr)
print("Normalized Array:", nor)  # Normalized array

Original Array:
 [1 2 3 4 5]
Mean: 3.0
St deviation: <function std at 0x0000024A306E5620>
Normalized Array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
